project:
  type: website
  render:
    - en/index.qmd
    - en/registration.qmd
    - en/call_for_presentations.qmd
    - en/author_guidelines.qmd
    - fr/index.qmd
    - fr/registration.qmd
    - fr/call_for_presentations.qmd
    - fr/author_guidelines.qmd
  output-dir: _site


website:
  title: "RSAfrica26"
  navbar:
    background: "#7C004C"
    foreground: "#FFFFFF"
    left:
      - text: "Home"
        href: en/index.qmd
      - text: "Call for presentations"
        href: en/call_for_presentations.qmd
      - text: "---"
      - text: "Accueil"
        href: fr/index.qmd
      - text: "Appel à Conférencier.es"
        href: fr/call_for_presentations.qmd
    right:
      - icon: github
        href: https://github.com/RSEAA/Research-Software-Africa


  page-footer:
    background: "#7C004C"
    foreground: "#FFFFFF"
    center: "Research Software Africa (RSAfrica26)"

format:
  html:
    theme:
      - cosmo
      - custom.scss
    toc: false
    page-layout: full
